version: "3.8"

services:
  compreface-postgres-db:
    image: postgres:11.5
    container_name: "compreface-postgres-db"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: frs
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - compreface-net

  compreface-admin:
    image: exadel/compreface-admin:1.2.0
    container_name: "compreface-admin"
    restart: always
    depends_on:
      - compreface-postgres-db
      - compreface-core
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_URL: jdbc:postgresql://compreface-postgres-db:5432/frs
      SPRING_PROFILES_ACTIVE: dev
      ENABLE_EMAIL_SERVER: false
      ADMIN_JAVA_OPTS: "-Xmx512m"
    ports:
      - "8085:8080"
    networks:
      - compreface-net

  compreface-core:
    image: exadel/compreface-core:1.2.0
    container_name: "compreface-core"
    restart: always
    depends_on:
      - compreface-postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_URL: jdbc:postgresql://compreface-postgres-db:5432/frs
      SPRING_PROFILES_ACTIVE: dev
      API_JAVA_OPTS: "-Xmx512m"
    ports:
      - "8000:3000"
    networks:
      - compreface-net

  compreface-ui:
    image: exadel/compreface-fe:1.2.0
    container_name: "compreface-ui"
    restart: always
    depends_on:
      - compreface-admin
      - compreface-core
    ports:
      - "8086:80"
    environment:
      - REACT_APP_API_URL=http://compreface-core:8000
      - CLIENT_MAX_BODY_SIZE=10M
      - PROXY_READ_TIMEOUT=300s
      - PROXY_CONNECT_TIMEOUT=300s
    volumes:
      - ./nginx.conf.template:/etc/nginx/templates/nginx.conf.template
    networks:
      - compreface-net

volumes:
  postgres-data:

networks:
  compreface-net: